#cloud-config
runcmd: []
datasource:
  Ec2:
    strict_id: false
ssh_pwauth: no
users:
  - name: {{secrets.YC_VM_USERNAME}}
    groups: sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - {{secrets.YC_VM_SSH}}
